plotDrawStyle10={   struct('color',[1,0,0],'lineStyle','-','Marker','square'),...
    struct('color',[0,1,0],'lineStyle','--','Marker','o'),...
    struct('color',[0,0,1],'lineStyle','-.','Marker','<'),...
    struct('color',[0,0,0],'lineStyle',':','Marker','>'),...% struct('color',[1,1,0],'lineStyle','-'),...%yellow
    struct('color',[1,0,1],'lineStyle','--','Marker','o'),...%pink
    struct('color',[0,1,1],'lineStyle','-.','Marker','<'),...
    struct('color',[0.5,0.5,0.5],'lineStyle','--','Marker','x'),...%gray-25%
    struct('color',[136,0,21]/255,'lineStyle','--','Marker','o'),...%dark red
    struct('color',[255,127,39]/255,'lineStyle','--','Marker','+'),...%orange
    struct('color',[0,162,232]/255,'lineStyle',':','Marker','>'),...%Turquoise
    };

% 42 lines style, if your trackers exceed this numbers, please add more
% line styles
plotDrawStyleAll={   struct('color',[1,0,0],'lineStyle','-'),...
    struct('color',[0,1,0],'lineStyle','-'),...
    struct('color',[0,1,1],'lineStyle','-'),...
    struct('color',[1,0,1],'lineStyle','-'),...%    struct('color',[1,1,0],'lineStyle','-'),...%yellow
    struct('color',[1,1,0],'lineStyle','-'),...%
    struct('color',[0,0,1],'lineStyle','-'),...
    struct('color',[0,162,232]/255,'lineStyle','-'),...%Turquoise
    struct('color',[163,73,164]/255,'lineStyle','-'),...%purple
    struct('color',[1,0,0],'lineStyle','-'),...%red
    struct('color',[0,162,232]/255,'lineStyle','--'),...%Turquoise
    struct('color',[163,73,164]/255,'lineStyle','--'),...%purple    %%%%%%%%%%%%%%%%%%%%
    struct('color',[1,0,0],'lineStyle','--'),...
    struct('color',[0,1,0],'lineStyle','--'),...
    struct('color',[0,0,1],'lineStyle','--'),...
    struct('color',[0,0,0],'lineStyle','--'),...%    struct('color',[1,1,0],'lineStyle','--'),...%yellow
    struct('color',[1,0,1],'lineStyle','--'),...%pink
    struct('color',[0,1,1],'lineStyle','--'),...
    struct('color',[0.5,0.5,0.5],'lineStyle','--'),...%gray-25%
    struct('color',[136,0,21]/255,'lineStyle','--'),...%dark red
    struct('color',[255,127,39]/255,'lineStyle','--'),...%orange
    struct('color',[0,162,232]/255,'lineStyle','--'),...%Turquoise
    struct('color',[163,73,164]/255,'lineStyle','--'),...%purple    %%%%%%%%%%%%%%%%%%%
    struct('color',[1,0,0],'lineStyle','-.'),...
    struct('color',[0,1,0],'lineStyle','-.'),...
    struct('color',[0,0,1],'lineStyle','-.'),...
    struct('color',[0,0,0],'lineStyle','-.'),...%    struct('color',[1,1,0],'lineStyle',':'),...%yellow
    struct('color',[1,0,1],'lineStyle','-.'),...%pink
    struct('color',[0,1,1],'lineStyle','-.'),...
    struct('color',[0.5,0.5,0.5],'lineStyle','-.'),...%gray-25%
    struct('color',[136,0,21]/255,'lineStyle','-.'),...%dark red
    struct('color',[255,127,39]/255,'lineStyle','-.'),...%orange
    struct('color',[0,162,232]/255,'lineStyle','-.'),...%Turquoise
    struct('color',[163,73,164]/255,'lineStyle','-.'),...%purple
    struct('color',[0,0,1],'lineStyle',':'),...
    struct('color',[0,1,0],'lineStyle',':'),...
    struct('color',[0,1,1],'lineStyle',':'),...
    struct('color',[1,0,1],'lineStyle',':'),...%    struct('color',[1,1,0],'lineStyle','-'),...%yellow
    struct('color',[1,1,0],'lineStyle',':'),...%
    struct('color',[1,0,0],'lineStyle',':'),...
    struct('color',[0,162,232]/255,'lineStyle',':'),...%Turquoise
    struct('color',[163,73,164]/255,'lineStyle',':'),...%purple
    struct('color',[1,0,0],'lineStyle',':') };